config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'help', to: 'pages#help'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://method.kz/">Web-programming course</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to "Twitter", '/', id: "logo" %>
      <nav>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <% if signed_in? %>
            <li><%= link_to "All Users", users_path %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
            </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/header' %>
    <div class="container">
        <%= render 'shared/flash_messages' %>
      <%= yield %>
      <%= debug params if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>